image: ruby:2.5.1
before_script:
  - apt-get update -qq && apt-get install -y -qq libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --without staging production
stages:
  - build

job_build:
  stage: build
  script:
    bundle exec rake
